version: '3.8'

services:
  app03:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:data/db.sqlite3
    volumes:
      - app03-data:/usr/local/bin/data
    restart: unless-stopped

volumes:
  app03-data: 