version: '3.8'

services:
  app05:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:data/db.sqlite3
      - SERVER_PORT=8080
    volumes:
      - app05-data:/usr/local/bin/data
    restart: unless-stopped

volumes:
  app05-data: 